### ISSUE TITLE
fixed sourcemap issue, but now prod build is broken

### ISSUE THREAD

**Issue by adamchenwei** [kitconcept/webpack-starter-angular#13]
Hi, author, 

I wanted to help merge this request in, I fixed a source map issue and added a build method for windows machine (it would not be able to put stop point when debugging in chrome), but now the prod build is broken, its a matter of  new webpack.SourceMapDevToolPlugin. Do you think I can somehow config it only for dev not for prod, so remove it from common? But I am not sure how to put it seperately into the prod webpack config. let me know Thanks

https://github.com/adamchenwei/webpack-starter-angular/compare/master...adamchenwei:feature/build-for-windows

**Comment by adamchenwei** [comment]
![image](https://cloud.githubusercontent.com/assets/4201698/17781934/4b2d0d0c-653f-11e6-9cdd-3e8858a309a7.png)

**Comment by tisto** [comment]
@adamchenwei please provide a full text traceback. No image, no cutted tracebacks please.

**Comment by tisto** [comment]
@adamchenwei I do not have any experience with Windows and I don't plan to support it. Therefore I will close the issue.
